### ISSUE TITLE
Anotações trocadas

### ISSUE THREAD

**Issue by DavidSheltonSF** [LeandroAlcantara-1997/URI_ONLINE_JUDGE-PYTHON#1]
Olá, acessei o seu repositório e percebi que as anotações dos seus 2 primeiros exercícios  [URI_1001.py](https://github.com/LeandroAlcantara-1997/URI_ONLINE_JUDGE-PYTHON/blob/main/URI_1001.py) e [URI_1002.py](https://github.com/LeandroAlcantara-1997/URI_ONLINE_JUDGE-PYTHON/blob/main/URI_1002.py) estão trocadas, isso pode confundir um pouco os iniciantes que quiserem aprender com os seus códigos.[](url)

**Comment by LeandroAlcantara-1997** [comment]
Ok @DavidSheltonSF , muito obrigado pela observação. Irei consertar.
